title: Wenxuan Zhang # your name (or website title) here
logo: "/recourses/profile.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Email: wxzhang@sas.upenn.edu
  <br><br>
  <a href=" ">Publications</a >
  <br><br>
  <a href="/projects">Projects</a >
  <br><br>
  <a href="recourses/CV.pdf">Resume</a >
  <br><br>
  <a href="/toy">Toy Examples</a >
theme: jekyll-theme-minimal
